// Code generated by kube-linter template codegen. DO NOT EDIT.
//go:build !templatecodegen
// +build !templatecodegen

package params

import (
	"golang.stackrox.io/kube-linter/pkg/check"
	"golang.stackrox.io/kube-linter/pkg/templates/util"
)

var (
	// Use some imports in case they don't get used otherwise.
	_ = util.MustParseParameterDesc

	ParamDescs = []check.ParameterDesc{}
)

func (p *Params) Validate() error { _ = "STUB: not implemented"; return nil }

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func(interface{}) (check.Func, error) {
	_ = "STUB: not implemented"
	return nil
}
