package main

import (
	"fmt"
	"os"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	"golang.stackrox.io/kube-linter/internal/set"
	"golang.stackrox.io/kube-linter/pkg/check"
	"k8s.io/gengo/types"
)

var (
	knownNonTemplateDirs = set.NewFrozenStringSet("all", "codegen", "util")
)

const (
	metadataMarker = "+"

	paramsStructName = "Params"
)

type templateElem struct {
	ParamDesc check.ParameterDesc
	ParamJSON string
}

const (
	fileTemplateStr = `// Code generated by kube-linter template codegen. DO NOT EDIT.
//go:build !templatecodegen
// +build !templatecodegen

package params

import (
	"fmt"
	"strings"

	"golang.stackrox.io/kube-linter/pkg/check"
	"golang.stackrox.io/kube-linter/pkg/templates/util"
)

var (
	// Use some imports in case they don't get used otherwise.
	_ = util.MustParseParameterDesc

{{- range . }}

	{{ .ParamDesc.Name}}ParamDesc = util.MustParseParameterDesc({{backtick}}
{{- .ParamJSON -}}
{{backtick}})
{{- end }}

	ParamDescs = []check.ParameterDesc{
		{{- range . }}
		{{ .ParamDesc.Name}}ParamDesc,
		{{- end }}
	}
)

func (p *Params) Validate() error {
	var validationErrors []string
	{{- range . }}
	{{- if eq .ParamDesc.Type "object" }}
	return fmt.Errorf("parameter validation not yet supported for object type \"{{ .ParamDesc.Key }}\"")
	{{- end }}
	{{- if .ParamDesc.Required }}
	{{- if ne .ParamDesc.Type "string" }}
	return fmt.Errorf("required parameter validation is currently only supported for strings, but {{ .ParamDesc.Key }} is not")
	{{- end }}
	if p.{{ .ParamDesc.XXXStructFieldName }} == "" {
		validationErrors = append(validationErrors, "required param {{.ParamDesc.Name}} not found")
	}
	{{- end }}
	{{- if .ParamDesc.Enum }}
	{{- if eq .ParamDesc.Type "array" }}
	for _, value := range p.{{ .ParamDesc.XXXStructFieldName }} {
		var found bool
		for _, allowedValue := range []string{
			{{- range .ParamDesc.Enum }}
			"{{ . }}",
			{{- end }}
		}{
			if value == allowedValue {
				found = true
				break
			}
		}
		if !found {
			validationErrors = append(validationErrors, fmt.Sprintf("param {{ .ParamDesc.Name }} has invalid value %q, must be one of {{ .ParamDesc.Enum }}", p.{{ .ParamDesc.XXXStructFieldName }}))
		}
	}
	{{- else }}
	var found bool
	for _, allowedValue := range []string{
		{{- range .ParamDesc.Enum }}
		"{{ . }}",
		{{- end }}
	}{
		if p.{{ .ParamDesc.XXXStructFieldName }} == allowedValue {
			found = true
			break
		}
	}
	if !found {
		validationErrors = append(validationErrors, fmt.Sprintf("param {{ .ParamDesc.Name }} has invalid value %q, must be one of {{ .ParamDesc.Enum }}", p.{{ .ParamDesc.XXXStructFieldName }}))
	}
	{{- end }}
	{{- end }}
	{{- end }}
	if len(validationErrors) > 0 {
		return fmt.Errorf("invalid parameters: %s", strings.Join(validationErrors, ", "))
    }
	return nil
}

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	var p Params
	if err := util.DecodeMapStructure(m, &p); err != nil {
		return nil, err
	}
	if err := p.Validate(); err != nil {
		return nil, err
	}
	return p, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func(interface{}) (check.Func, error) {
	return func(paramsInt interface{}) (check.Func, error) {
		return f(paramsInt.(Params))
	}
}
`
)

var (
	fileTemplate = template.Must(template.New("gen").Funcs(sprig.TxtFuncMap()).Funcs(template.FuncMap{
		"backtick": func() string {
			return "`"
		},
	}).Parse(fileTemplateStr))
)

func lowerCaseFirstLetter(s string) string { _ = "STUB: not implemented"; return "" }

func getName(member types.Member) string { _ = "STUB: not implemented"; return "" }

func getDescription(member types.Member) string { _ = "STUB: not implemented"; return "" }

func setBoolBasedOnPresenceOfTag(valToSet *bool, tag string, extractedTags map[string][]string) error {
	_ = "STUB: not implemented"
	return nil
}

func constructParameterDescsFromStruct(typeSpec *types.Type) ([]check.ParameterDesc, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// For now we only support array of builtin types. No array of objects or array of arrays.

func getCheckTypeFromParsedBuiltinType(typeSpec *types.Type) (check.ParameterType, error) {
	_ = "STUB: not implemented"
	return *new(check.ParameterType), nil
}

func processTemplate(dir string) error {
	_ = "STUB: not implemented"

	// This avoids parsing generated files in the package (since we add +build !templatecodegen to them,
	// which makes the parsing much quicker since the parser doesn't have to load any imported packages).
	return nil
}

func mainCmd() error { _ = "STUB: not implemented"; return nil }

func main() {
	if err := mainCmd(); err != nil {
		fmt.Printf("Error executing command: %v", err)
		os.Exit(1)
	}

}
