// Code generated by genny. DO NOT EDIT.
// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package set

// If you want to add a set for your custom type, simply add another go generate line along with the
// existing ones. If you're creating a set for a primitive type, you can follow the example of "string"
// and create the generated file in this package.
// For non-primitive sets, please make the generated code files go outside this package.
// Sometimes, you might need to create it in the same package where it is defined to avoid import cycles.
// The permission set is an example of how to do that.
// You can also specify the -imp command to specify additional imports in your generated file, if required.

// string represents a generic type that we want to have a set of.

// StringSet will get translated to generic sets.
type StringSet map[string]struct{}

// Add adds an element of type string.
func (k *StringSet) Add(i string) bool { _ = "STUB: not implemented"; return false }

// AddMatching is a utility function that adds all the elements that match the given function to the set.
func (k *StringSet) AddMatching(matchFunc func(string) bool, elems ...string) bool {
	_ = "STUB: not implemented"
	return false
}

// AddAll adds all elements of type string. The return value is true if any new element
// was added.
func (k *StringSet) AddAll(is ...string) bool { _ = "STUB: not implemented"; return false }

// Remove removes an element of type string.
func (k *StringSet) Remove(i string) bool { _ = "STUB: not implemented"; return false }

// RemoveAll removes the given elements.
func (k *StringSet) RemoveAll(is ...string) bool { _ = "STUB: not implemented"; return false }

// RemoveMatching removes all elements that match a given predicate.
func (k *StringSet) RemoveMatching(pred func(string) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// Contains returns whether the set contains an element of type string.
func (k StringSet) Contains(i string) bool { _ = "STUB: not implemented"; return false }

// Cardinality returns the number of elements in the set.
func (k StringSet) Cardinality() int {
	_ = "STUB: not implemented"

	// IsEmpty returns whether the underlying set is empty (includes uninitialized).
	return 0
}

func (k StringSet) IsEmpty() bool {
	_ = "STUB: not implemented"

	// Clone returns a copy of this set.
	return false
}

func (k StringSet) Clone() StringSet { _ = "STUB: not implemented"; return *new(StringSet) }

// Difference returns a new set with all elements of k not in other.
func (k StringSet) Difference(other StringSet) StringSet {
	_ = "STUB: not implemented"
	return *new(StringSet)
}

// Helper function for intersections.
func (k StringSet) getSmallerLargerAndMaxIntLen(other StringSet) (smaller StringSet, larger StringSet, maxIntLen int) {
	_ = "STUB: not implemented"
	return *new(StringSet), *new(StringSet), 0
}

// Intersects returns whether the set has a non-empty intersection with the other set.
func (k StringSet) Intersects(other StringSet) bool { _ = "STUB: not implemented"; return false }

// Intersect returns a new set with the intersection of the members of both sets.
func (k StringSet) Intersect(other StringSet) StringSet {
	_ = "STUB: not implemented"
	return *new(StringSet)
}

// Union returns a new set with the union of the members of both sets.
func (k StringSet) Union(other StringSet) StringSet {
	_ = "STUB: not implemented"
	return *new(StringSet)
}

// Equal returns a bool if the sets are equal
func (k StringSet) Equal(other StringSet) bool { _ = "STUB: not implemented"; return false }

// AsSlice returns a slice of the elements in the set. The order is unspecified.
func (k StringSet) AsSlice() []string { _ = "STUB: not implemented"; return nil }

// GetArbitraryElem returns an arbitrary element from the set.
// This can be useful if, for example, you know the set has exactly one
// element, and you want to pull it out.
// If the set is empty, the zero value is returned.
func (k StringSet) GetArbitraryElem() (arbitraryElem string) { _ = "STUB: not implemented"; return "" }

// AsSortedSlice returns a slice of the elements in the set, sorted using the passed less function.
func (k StringSet) AsSortedSlice(less func(i, j string) bool) []string {
	_ = "STUB: not implemented"
	return nil
}

// Since we're generating the code, we might as well use sort.Sort
// and avoid paying the reflection penalty of sort.Slice.

// Clear empties the set
func (k *StringSet) Clear() {
	_ = "STUB: not implemented"

	// Freeze returns a new, frozen version of the set.
	return
}

func (k StringSet) Freeze() FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// ElementsString returns a string representation of all elements, with individual element strings separated by `sep`.
// The string representation of an individual element is obtained via `fmt.Fprint`.
func (k StringSet) ElementsString(sep string) string { _ = "STUB: not implemented"; return "" }

// NewStringSet returns a new thread unsafe set with the given key type.
func NewStringSet(initial ...string) StringSet { _ = "STUB: not implemented"; return *new(StringSet) }

type sortableStringSlice struct {
	slice []string
	less  func(i, j string) bool
}

func (s *sortableStringSlice) Len() int { _ = "STUB: not implemented"; return 0 }

func (s *sortableStringSlice) Less(i, j int) bool { _ = "STUB: not implemented"; return false }

func (s *sortableStringSlice) Swap(i, j int) { _ = "STUB: not implemented"; return }

// A FrozenStringSet is a frozen set of string elements, which
// cannot be modified after creation. This allows users to use it as if it were
// a "const" data structure, and also makes it slightly more optimal since
// we don't have to lock accesses to it.
type FrozenStringSet struct {
	underlying map[string]struct{}
}

// NewFrozenStringSetFromMap returns a new frozen set from the set-style map.
func NewFrozenStringSetFromMap(m map[string]struct{}) FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// NewFrozenStringSet returns a new frozen set with the provided elements.
func NewFrozenStringSet(elements ...string) FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// Contains returns whether the set contains the element.
func (k FrozenStringSet) Contains(elem string) bool { _ = "STUB: not implemented"; return false }

// Cardinality returns the cardinality of the set.
func (k FrozenStringSet) Cardinality() int { _ = "STUB: not implemented"; return 0 }

// IsEmpty returns whether the underlying set is empty (includes uninitialized).
func (k FrozenStringSet) IsEmpty() bool { _ = "STUB: not implemented"; return false }

// AsSlice returns the elements of the set. The order is unspecified.
func (k FrozenStringSet) AsSlice() []string { _ = "STUB: not implemented"; return nil }

// AsSortedSlice returns the elements of the set as a sorted slice.
func (k FrozenStringSet) AsSortedSlice(less func(i, j string) bool) []string {
	_ = "STUB: not implemented"
	return nil
}

// Since we're generating the code, we might as well use sort.Sort
// and avoid paying the reflection penalty of sort.Slice.

// ElementsString returns a string representation of all elements, with individual element strings separated by `sep`.
// The string representation of an individual element is obtained via `fmt.Fprint`.
func (k FrozenStringSet) ElementsString(sep string) string { _ = "STUB: not implemented"; return "" }

// The following functions make use of casting `k.underlying` into a mutable Set. This is safe, since we never leak
// references to these objects, and only invoke mutable set methods that are guaranteed to return a new copy.

// Union returns a frozen set that represents the union between this and other.
func (k FrozenStringSet) Union(other FrozenStringSet) FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// Intersect returns a frozen set that represents the intersection between this and other.
func (k FrozenStringSet) Intersect(other FrozenStringSet) FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// Difference returns a frozen set that represents the set difference between this and other.
func (k FrozenStringSet) Difference(other FrozenStringSet) FrozenStringSet {
	_ = "STUB: not implemented"
	return *new(FrozenStringSet)
}

// Unfreeze returns a mutable set with the same contents as this frozen set. This set will not be affected by any
// subsequent modifications to the returned set.
func (k FrozenStringSet) Unfreeze() StringSet { _ = "STUB: not implemented"; return *new(StringSet) }
