// Code generated by kube-linter template codegen. DO NOT EDIT.
//go:build !templatecodegen
// +build !templatecodegen

package params

import (
	"golang.stackrox.io/kube-linter/pkg/check"
	"golang.stackrox.io/kube-linter/pkg/templates/util"
)

var (
	// Use some imports in case they don't get used otherwise.
	_ = util.MustParseParameterDesc

	dirsParamDesc = util.MustParseParameterDesc(`{
	"Name": "dirs",
	"Type": "array",
	"Description": "An array of regular expressions specifying system directories to be mounted on containers. e.g. ^/usr$ for /usr",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": true,
	"XXXStructFieldName": "Dirs",
	"XXXIsPointer": false
}
`)

	ParamDescs = []check.ParameterDesc{
		dirsParamDesc,
	}
)

func (p *Params) Validate() error { _ = "STUB: not implemented"; return nil }

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func(interface{}) (check.Func, error) {
	_ = "STUB: not implemented"
	return nil
}
