// Code generated by kube-linter flag codegen. DO NOT EDIT.
//go:build !flagcodegen
// +build !flagcodegen

package config

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// AddFlags, walks through config.Check struct and bind its Member to Cobra command
// and add respective Viper flag
func AddFlags(c *cobra.Command, v *viper.Viper) { _ = "STUB: not implemented"; return }
