package main

import (
	"fmt"
	"os"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	"k8s.io/gengo/types"
)

const (
	metadataMarker   = "+"
	flagNameTagKey   = "flagName"
	paramsStructName = "Config"
)

const (
	fileTemplateStr = `// Code generated by kube-linter flag codegen. DO NOT EDIT.
// +build !flagcodegen

package config

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// AddFlags, walks through config.Check struct and bind its Member to Cobra command 
// and add respective Viper flag 
func AddFlags(c *cobra.Command, v *viper.Viper) {
	{{- range . }}
	c.Flags().{{ .FlagDesc.CobraType }}("{{ .FlagDesc.Name }}", {{ defaultVal .FlagDesc.CobraType }}, "{{ .FlagDesc.Description }}")
	if err := v.BindPFlag("{{ .FlagDesc.JSONPath }}", c.Flags().Lookup("{{ .FlagDesc.Name }}")); err != nil {
		panic(err)
	}

	{{- end }}
}
`
)

var (
	fileTemplate = template.Must(
		template.New("gen").
			Funcs(sprig.TxtFuncMap()).
			Funcs(template.FuncMap{"defaultVal": mustGetDefaultValueRepr}).
			Parse(fileTemplateStr),
	)
)

// These types are used in template to add appropriate Cobra flags
var (
	stringType  = newFlagType("String", `""`)
	intType     = newFlagType("Int", "0")
	boolType    = newFlagType("Bool", "false")
	float32Type = newFlagType("Float32", "0")
	float64Type = newFlagType("Float64", "0")

	stringSliceType = newFlagType("StringSlice", "nil")

	defaultValueReprsByTypeName = make(map[string]string)
)

func mustGetDefaultValueRepr(typeName string) string { _ = "STUB: not implemented"; return "" }

func newFlagType(typeName, defaultValueRepr string) string { _ = "STUB: not implemented"; return "" }

type flagDesc struct {
	Name        string
	JSONPath    string
	Description string
	CobraType   string
}

type templateElem struct {
	FlagDesc flagDesc
}

func getJSONKey(member types.Member) (string, error) { _ = "STUB: not implemented"; return "", nil }

func getDescription(member types.Member) string { _ = "STUB: not implemented"; return "" }

func getCobraTypeFromMember(memberType *types.Type) string { _ = "STUB: not implemented"; return "" }

func constructFlagDescsFromStruct(typeSpec *types.Type, jsonPathSoFar []string) ([]flagDesc, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// If we got here, it must be a primitive field.

func mainCmd() error { _ = "STUB: not implemented"; return nil }

// This avoids parsing generated files in the package (since we add +build !flagcodegen to them,
// which makes the parsing much quicker since the parser doesn't have to load any imported packages).

func main() {
	if err := mainCmd(); err != nil {
		fmt.Printf("Error executing command: %v", err)
		os.Exit(1)
	}
}
